# Generated by Django 4.2.11 on 2024-07-11 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_submodulo2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submodulo2',
        ),
    ]
