# Generated by Django 4.2.11 on 2024-07-08 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planta', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(default='', max_length=255, unique=True)),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('cliente_sage', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen_usuario', models.ImageField(blank=True, null=True, upload_to='usuarios/')),
                ('codigo_empleado', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_moneda', models.CharField(blank=True, max_length=255, null=True)),
                ('id_colaborador', models.CharField(blank=True, max_length=255, null=True)),
                ('idioma', models.CharField(blank=True, max_length=255, null=True)),
                ('default_poolid', models.CharField(blank=True, max_length=255, null=True)),
                ('ubicacion_contenedores', models.CharField(blank=True, max_length=255, null=True)),
                ('ubicacion_destino_produccion', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('default_planta', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='default_planta', to='planta.planta')),
                ('empresa', models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='usuarios', to='empresa.empresa')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
