# Generated by Django 4.2.11 on 2024-07-12 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0003_delete_submodulo2'),
        ('user', '0002_useraccount_username_alter_useraccount_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSubmodulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submodulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.submodulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.modulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='modulos',
            field=models.ManyToManyField(through='user.UsuarioModulo', to='modulos.modulo'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='submodulos',
            field=models.ManyToManyField(through='user.UsuarioSubmodulo', to='modulos.submodulo'),
        ),
    ]
