# Generated by Django 4.2.11 on 2024-07-12 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0003_delete_submodulo2'),
        ('user', '0003_usuariosubmodulo_usuariomodulo_useraccount_modulos_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuariomodulo',
            unique_together={('usuario', 'modulo')},
        ),
        migrations.AlterUniqueTogether(
            name='usuariosubmodulo',
            unique_together={('usuario', 'submodulo')},
        ),
    ]
