# Generated by Django 4.2.11 on 2024-07-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usuariomodulo_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuariomodulo',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='usuariosubmodulo',
            unique_together=set(),
        ),
    ]
