# Generated by Django 4.2.11 on 2024-07-12 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_empresamodulo_unique_together_and_more'),
        ('planta', '0001_initial'),
        ('user', '0007_alter_useraccount_default_planta_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuariomodulo',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='usuariosubmodulo',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='default_planta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='default_planta', to='planta.planta'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='usuarios', to='empresa.empresa'),
        ),
    ]
