# Generated by Django 4.2.11 on 2024-07-24 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0004_submodulo2'),
        ('user', '0008_alter_usuariomodulo_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSubmodulo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submodulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.submodulo2')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='submodulos2',
            field=models.ManyToManyField(through='user.UsuarioSubmodulo2', to='modulos.submodulo2'),
        ),
    ]
