# Generated by Django 4.2.11 on 2024-09-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_usuariosubmodulo2_useraccount_submodulos2'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='interno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='partner',
            field=models.BooleanField(default=False),
        ),
    ]
