# Generated by Django 4.2.11 on 2024-10-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_useraccount_interno_useraccount_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='default_planta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
