# Generated by Django 4.2.11 on 2024-05-21 11:27

from django.db import migrations, models
import django.db.models.deletion

def create_default_empresa(apps, schema_editor):
    Empresa = apps.get_model('empresa', 'Empresa')
    Empresa.objects.create(
        nombre='NUNSYS',
        api_endpoint='https://sagex3.nunsys.com:7777/soap-generic/syracuse/collaboration/syracuse/CAdxWebServiceXmlCC',
        suscripcion='FREE'
    )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('api_endpoint', models.URLField(max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen_background', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('imagen_corporativa', models.ImageField(blank=True, null=True, upload_to='corporativas/')),
                ('suscripcion', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PRO', 'Pro'), ('INFINITY', 'Infinity')], default='FREE', max_length=10)),
                ('usuarios_creados', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaSubmodulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
                ('submodulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.submodulo')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.modulo')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='modulos',
            field=models.ManyToManyField(through='empresa.EmpresaModulo', to='modulos.modulo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='submodulos',
            field=models.ManyToManyField(through='empresa.EmpresaSubmodulo', to='modulos.submodulo'),
        ),
        migrations.RunPython(create_default_empresa),
    ]
