# Generated by Django 4.2.11 on 2024-07-08 10:18

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255)),
                ('api_endpoint', models.URLField(blank=True, max_length=500, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('descripcion', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('imagen_background', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('imagen_corporativa', models.ImageField(blank=True, null=True, upload_to='corporativas/')),
                ('suscripcion', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PRO', 'Pro'), ('INFINITY', 'Infinity')], default='FREE', max_length=10)),
                ('usuarios_creados', models.PositiveIntegerField(default=0)),
                ('campo_familia', models.CharField(blank=True, max_length=255, null=True)),
                ('campo_subfamilia', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_tabla_traducciones', models.CharField(blank=True, max_length=255, null=True)),
                ('decimales_consumo', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('decimales_stock', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('end_point', models.URLField(blank=True, max_length=500, null=True)),
                ('mostrar_articulos_activos', models.BooleanField(default=True)),
                ('mostrar_clientes_activos', models.BooleanField(default=True)),
                ('mostrar_proveedores_activos', models.BooleanField(default=True)),
                ('passwordws', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_pedido_catalogo', models.CharField(blank=True, max_length=255, null=True)),
                ('usuariows', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaSubmodulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
                ('submodulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.submodulo')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.modulo')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='modulos',
            field=models.ManyToManyField(through='empresa.EmpresaModulo', to='modulos.modulo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='submodulos',
            field=models.ManyToManyField(through='empresa.EmpresaSubmodulo', to='modulos.submodulo'),
        ),
    ]
