# Generated by Django 4.2.11 on 2024-07-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_submodulo2'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='empresamodulo',
            unique_together={('empresa', 'modulo')},
        ),
        migrations.AlterUniqueTogether(
            name='empresasubmodulo',
            unique_together={('empresa', 'submodulo')},
        ),
    ]
