# Generated by Django 4.2.11 on 2024-07-24 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0004_submodulo2'),
        ('empresa', '0002_alter_empresamodulo_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaSubmodulo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
                ('submodulo2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.submodulo2')),
            ],
            options={
                'unique_together': {('empresa', 'submodulo2')},
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='submodulos2',
            field=models.ManyToManyField(through='empresa.EmpresaSubmodulo2', to='modulos.submodulo2'),
        ),
    ]
